### ISSUE TITLE
Why did you use useDispatch directly from react-redux? and not own redux

### ISSUE THREAD

**Issue by kharikbo** [UmttikhinaDasha/IT-Bookstore#1]
Привет!

Если я правильно понял, вы вынесли работу с функциями `react-redux` в отдельный слой абстракции, который находиться  

> src/shared/lib/store/redux.ts

Не знаю на сколько осознанно, но почему вы здесь используются `useDispatch ` напрямую из `react-redux`? а не из своего слоя абстракции, как везде собственно. Возможно здесь есть просто какой-то скрытый смысл :)

https://github.com/UmttikhinaDasha/IT-Bookstore/blob/7cefe4172650156e7be17ba167d124737a38707f/src/pages/cart/ui/cart.tsx#L1

**Comment by UmttikhinaDasha** [comment]
Привет! 
Да, это действительно была ошибка, спасибо, что заметил
